# Generated by Django 3.2.8 on 2022-04-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='achieve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('stepen', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('about', models.CharField(max_length=500)),
                ('link', models.URLField(max_length=300)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображения')),
            ],
        ),
    ]
